# Predicting Credit Card Default Rates using Ensembles

Dataset has 1000 rows and 17 columns

(1 = Good, 2 = Bad) 

The rows represent the actual classification and the columns the predicted classification. 

It is worse to class a customer as good when they are bad (5), than it is to class a customer as bad when they are good (1). 

Attribute Information:
Attribute 1: (qualitative) 
Status of existing checking account 
A11 : ... < 0 DM 
A12 : 0 <= ... < 200 DM 
A13 : ... >= 200 DM / salary assignments for at least 1 year 
A14 : no checking account 

Attribute 2: (numerical) 
Duration in month 

Attribute 3: (qualitative) 
Credit history 
A30 : no credits taken/ all credits paid back duly 
A31 : all credits at this bank paid back duly 
A32 : existing credits paid back duly till now 
A33 : delay in paying off in the past 
A34 : critical account/ other credits existing (not at this bank) 

Attribute 4: (qualitative) 
Purpose 
A40 : car (new) 
A41 : car (used) 
A42 : furniture/equipment 
A43 : radio/television 
A44 : domestic appliances 
A45 : repairs 
A46 : education 
A47 : (vacation - does not exist?) 
A48 : retraining 
A49 : business 
A410 : others 

Attribute 5: (numerical) 
Credit amount 

Attibute 6: (qualitative) 
Savings account/bonds 
A61 : ... < 100 DM 
A62 : 100 <= ... < 500 DM 
A63 : 500 <= ... < 1000 DM 
A64 : .. >= 1000 DM 
A65 : unknown/ no savings account 

Attribute 7: (qualitative) 
Present employment since 
A71 : unemployed 
A72 : ... < 1 year 
A73 : 1 <= ... < 4 years 
A74 : 4 <= ... < 7 years 
A75 : .. >= 7 years 

Attribute 8: (numerical) 
Installment rate in percentage of disposable income 

Attribute 9: (qualitative) 
Personal status and sex 
A91 : male : divorced/separated 
A92 : female : divorced/separated/married 
A93 : male : single 
A94 : male : married/widowed 
A95 : female : single 

Attribute 10: (qualitative) 
Other debtors / guarantors 
A101 : none 
A102 : co-applicant 
A103 : guarantor 

Attribute 11: (numerical) 
Present residence since 

Attribute 12: (qualitative) 
Property 
A121 : real estate 
A122 : if not A121 : building society savings agreement/ life insurance 
A123 : if not A121/A122 : car or other, not in attribute 6 
A124 : unknown / no property 

Attribute 13: (numerical) 
Age in years 

Attribute 14: (qualitative) 
Other installment plans 
A141 : bank 
A142 : stores 
A143 : none 

Attribute 15: (qualitative) 
Housing 
A151 : rent 
A152 : own 
A153 : for free 

Attribute 16: (numerical) 
Number of existing credits at this bank 

Attribute 17: (qualitative) 
Job 
A171 : unemployed/ unskilled - non-resident 
A172 : unskilled - resident 
A173 : skilled employee / official 
A174 : management/ self-employed/ 
highly qualified employee/ officer 

Attribute 18: (numerical) 
Number of people being liable to provide maintenance for 

Attribute 19: (qualitative) 
Telephone 
A191 : none 
A192 : yes, registered under the customers name 

Attribute 20: (qualitative) 
foreign worker 
A201 : yes 
A202 : no 

In [1]:
#Always import this if before the libraries
%matplotlib inline

In [1]:
import numpy as np
import pandas as pd
# calculate accuracy measures and confusion matrix
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
#DT does not take strings as input for the model fit step
from sklearn.feature_extraction.text import CountVectorizer  

# Data Preprocessing

In [2]:
credit_df = pd.read_csv("credit.csv")

In [3]:
credit_df.describe().transpose()

count      mean          std    min     25%     50%  \
months_loan_duration  1000.0    20.903    12.058814    4.0    12.0    18.0   
amount                1000.0  3271.258  2822.736876  250.0  1365.5  2319.5   
percent_of_income     1000.0     2.973     1.118715    1.0     2.0     3.0   
years_at_residence    1000.0     2.845     1.103718    1.0     2.0     3.0   
age                   1000.0    35.546    11.375469   19.0    27.0    33.0   
existing_loans_count  1000.0     1.407     0.577654    1.0     1.0     1.0   
dependents            1000.0     1.155     0.362086    1.0     1.0     1.0   

                          75%      max  
months_loan_duration    24.00     72.0  
amount                3972.25  18424.0  
percent_of_income        4.00      4.0  
years_at_residence       4.00      4.0  
age                     42.00     75.0  
existing_loans_count     2.00      4.0  
dependents               1.00      2.0

In [5]:
credit_df.head(10)  #let us look at the raw data. As is evident, there are lot of missing values 

checking_balance  months_loan_duration credit_history               purpose  \
0           < 0 DM                     6       critical  furniture/appliances   
1       1 - 200 DM                    48           good  furniture/appliances   
2          unknown                    12       critical             education   
3           < 0 DM                    42           good  furniture/appliances   
4           < 0 DM                    24           poor                   car   
5          unknown                    36           good             education   
6          unknown                    24           good  furniture/appliances   
7       1 - 200 DM                    36           good                   car   
8          unknown                    12           good  furniture/appliances   
9       1 - 200 DM                    30       critical                   car   

   amount savings_balance employment_duration  percent_of_income  \
0    1169         unknown           > 7 years                  4   
1    5951        < 100 DM         1 - 4 years                  2   
2    2096        < 100 DM         4 - 7 years                  2   
3    7882        < 100 DM         4 - 7 years                  2   
4    4870        < 100 DM         1 - 4 years                  3   
5    9055         unknown         1 - 4 years                  2   
6    2835   500 - 1000 DM           > 7 years                  3   
7    6948        < 100 DM         1 - 4 years                  2   
8    3059       > 1000 DM         4 - 7 years                  2   
9    5234        < 100 DM          unemployed                  4   

   years_at_residence  age other_credit housing  existing_loans_count  \
0                   4   67         none     own                     2   
1                   2   22         none     own                     1   
2                   3   49         none     own                     1   
3                   4   45         none   other                     1   
4                   4   53         none   other                     2   
5                   4   35         none   other                     1   
6                   4   53         none     own                     1   
7                   2   35         none    rent                     1   
8                   4   61         none     own                     1   
9                   2   28         none     own                     2   

          job  dependents phone default  
0     skilled           1   yes      no  
1     skilled           1    no     yes  
2   unskilled           2    no      no  
3     skilled           2    no      no  
4     skilled           2    no     yes  
5   unskilled           2   yes      no  
6     skilled           1    no      no  
7  management           1   yes      no  
8   unskilled           1    no      no  
9  management           1    no     yes

In [6]:
credit_df.shape

(1000, 17)

In [7]:
credit_df.describe(include=[np.number])


months_loan_duration        amount  percent_of_income  \
count           1000.000000   1000.000000        1000.000000   
mean              20.903000   3271.258000           2.973000   
std               12.058814   2822.736876           1.118715   
min                4.000000    250.000000           1.000000   
25%               12.000000   1365.500000           2.000000   
50%               18.000000   2319.500000           3.000000   
75%               24.000000   3972.250000           4.000000   
max               72.000000  18424.000000           4.000000   

       years_at_residence          age  existing_loans_count   dependents  
count         1000.000000  1000.000000           1000.000000  1000.000000  
mean             2.845000    35.546000              1.407000     1.155000  
std              1.103718    11.375469              0.577654     0.362086  
min              1.000000    19.000000              1.000000     1.000000  
25%              2.000000    27.000000              1.000000     1.000000  
50%              3.000000    33.000000              1.000000     1.000000  
75%              4.000000    42.000000              2.000000     1.000000  
max              4.000000    75.000000              4.000000     2.000000

In [8]:
credit_df.info()  # many columns are of type object i.e. strings. These need to be converted to ordinal type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
checking_balance        1000 non-null object
months_loan_duration    1000 non-null int64
credit_history          1000 non-null object
purpose                 1000 non-null object
amount                  1000 non-null int64
savings_balance         1000 non-null object
employment_duration     1000 non-null object
percent_of_income       1000 non-null int64
years_at_residence      1000 non-null int64
age                     1000 non-null int64
other_credit            1000 non-null object
housing                 1000 non-null object
existing_loans_count    1000 non-null int64
job                     1000 non-null object
dependents              1000 non-null int64
phone                   1000 non-null object
default                 1000 non-null object
dtypes: int64(7), object(10)
memory usage: 132.9+ KB


In [9]:
# Decision tree in Python can take only numerical / categorical colums. It cannot take string / obeject types. 
# The following code loops through each column and checks if the column type is object then converts those columns
# into categorical with each distinct value becoming a category or code.

for feature in credit_df.columns: # Loop through all columns in the dataframe
    if credit_df[feature].dtype == 'object': # Only apply for columns with categorical strings
        credit_df[feature] = pd.Categorical(credit_df[feature]).codes # Replace strings with an integer

In [10]:
credit_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
checking_balance        1000 non-null int8
months_loan_duration    1000 non-null int64
credit_history          1000 non-null int8
purpose                 1000 non-null int8
amount                  1000 non-null int64
savings_balance         1000 non-null int8
employment_duration     1000 non-null int8
percent_of_income       1000 non-null int64
years_at_residence      1000 non-null int64
age                     1000 non-null int64
other_credit            1000 non-null int8
housing                 1000 non-null int8
existing_loans_count    1000 non-null int64
job                     1000 non-null int8
dependents              1000 non-null int64
phone                   1000 non-null int8
default                 1000 non-null int8
dtypes: int64(7), int8(10)
memory usage: 64.5 KB


In [12]:
# Pairplot using sns
# import seaborn as sns
# sns.pairplot(credit_df, hue = "default")

In [13]:
col_labels = [ 'checking_balance', 'months_loan_duration' ,'credit_history' , 'purpose, amount', 'savings_balance' , 'employment_duration'
, 'percent_of_income', 'years_at_residence', 'age', 'other_credit', 'housing', 'existing_loans_count', 'job', 'dependents', 'phone', 'default']

In [14]:
train_char_label = ['No', 'Yes']

In [15]:
# capture the target column ("default") into separate vectors for training set and test set

X = credit_df.drop("default" , axis=1)

y = credit_df.pop("default")




In [16]:
# splitting data into training and test set for independent attributes
from sklearn.model_selection import train_test_split

X_train, X_test, train_labels, test_labels = train_test_split(X, y, test_size=.30, random_state=1)


In [17]:
# invoking the decision tree classifier function. Using 'entropy' method of finding the split columns. Other option 
# could be gini index.  Restricting the depth of the tree to 5 (no particular reason for selecting this)

#dt_model = DecisionTreeClassifier(criterion = 'entropy' , max_depth = 5, random_state = 100)
                                  
dt_model = DecisionTreeClassifier(criterion = 'entropy' )

In [19]:
dt_model.fit(X_train, train_labels)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [22]:
from IPython.display import Image  
#import pydotplus as pydot
from sklearn import tree
from os import system

Credit_Tree_File = open('d:\credit_tree.dot','w')
dot_data = tree.export_graphviz(dt_model, out_file=Credit_Tree_File, feature_names = list(X_train), class_names = list(train_char_label))

Credit_Tree_File.close()

# importance of features in the tree building ( The importance of a feature is computed as the 
#(normalized) total reduction of the criterion brought by that feature. It is also known as the Gini importance )

print (pd.DataFrame(dt_model.feature_importances_, columns = ["Imp"], index = X_train.columns))


                           Imp
checking_balance      0.122194
months_loan_duration  0.068224
credit_history        0.066657
purpose               0.066136
amount                0.200756
savings_balance       0.084224
employment_duration   0.038207
percent_of_income     0.038241
years_at_residence    0.049381
age                   0.111005
other_credit          0.045786
housing               0.007996
existing_loans_count  0.028725
job                   0.037778
dependents            0.024258
phone                 0.010430


In [20]:
# You can also copy the script in the .dot file and paste it at http://webgraphviz.com/ to get tree view 
#or create a .png as below

# system("dot -Tpng D:\credit_tree.dot -o D:/credit_tree.png")
# Image("d:\credit_tree.png")

In [24]:
y_predict = dt_model.predict(X_test)

In [25]:
print(dt_model.score(X_train , train_labels))
print(dt_model.score(X_test , test_labels))

1.0
0.67


In [26]:
print(metrics.confusion_matrix(test_labels, y_predict))

[[166  48]
 [ 51  35]]


In [27]:
# Look at the class level metric for the defaulter class. It is poor. 

#                                      Regularising the Decision Tree

In [28]:

reg_dt_model = DecisionTreeClassifier(criterion = 'entropy', max_depth = 7)
reg_dt_model.fit(X_train, train_labels)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=7,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [29]:
credit_tree_regularized = open('d:\credit_tree_regularized.dot','w')
dot_data = tree.export_graphviz(reg_dt_model, out_file= credit_tree_regularized , feature_names = list(X_train), class_names = list(train_char_label))

credit_tree_regularized.close()

print (pd.DataFrame(dt_model.feature_importances_, columns = ["Imp"], index = X_train.columns))


                           Imp
checking_balance      0.122194
months_loan_duration  0.068224
credit_history        0.066657
purpose               0.066136
amount                0.200756
savings_balance       0.084224
employment_duration   0.038207
percent_of_income     0.038241
years_at_residence    0.049381
age                   0.111005
other_credit          0.045786
housing               0.007996
existing_loans_count  0.028725
job                   0.037778
dependents            0.024258
phone                 0.010430


In [30]:
# You can also copy the script in the .dot file and paste it at http://webgraphviz.com/ to get tree view
# or create a .png as below
# system("dot -Tpng D:\credit_tree_regularized.dot -o D:/credit_tree_regularized.png")
# Image("d:\credit_tree_regularized.png")

In [31]:
y_predict = reg_dt_model.predict(X_test)

In [32]:
reg_dt_model.score(X_test , test_labels)

0.6933333333333334

In [33]:
print(metrics.confusion_matrix(test_labels, y_predict))

[[172  42]
 [ 50  36]]


#                             Ensemble Learning - Bagging

In [34]:
from sklearn.ensemble import BaggingClassifier

bgcl = BaggingClassifier(base_estimator=dt_model, n_estimators=50)

#bgcl = BaggingClassifier(n_estimators=50)
bgcl = bgcl.fit(X_train, train_labels)


In [35]:
y_predict = bgcl.predict(X_test)

print(bgcl.score(X_test , test_labels))

print(metrics.confusion_matrix(test_labels, y_predict))

0.7466666666666667
[[185  29]
 [ 47  39]]


# Ensemble Learning - AdaBoosting

In [36]:
from sklearn.ensemble import AdaBoostClassifier
abcl = AdaBoostClassifier(base_estimator=dt_model, n_estimators=10)
#abcl = AdaBoostClassifier( n_estimators=50)
abcl = abcl.fit(X_train, train_labels)


In [37]:
y_predict = abcl.predict(X_test)
print(abcl.score(X_test , test_labels))

print(metrics.confusion_matrix(test_labels, y_predict))

0.6433333333333333
[[159  55]
 [ 52  34]]


#                     Ensemble Learning - GradientBoost

In [38]:
from sklearn.ensemble import GradientBoostingClassifier
gbcl = GradientBoostingClassifier(n_estimators = 50)
gbcl = gbcl.fit(X_train, train_labels)


In [39]:
y_predict = gbcl.predict(X_test)
print(gbcl.score(X_test , test_labels))
print(metrics.confusion_matrix(test_labels, y_predict))

0.73
[[190  24]
 [ 57  29]]


# Ensemble RandomForest Classifier

In [40]:
from sklearn.ensemble import RandomForestClassifier
rfcl = RandomForestClassifier(n_estimators = 50)
rfcl = rfcl.fit(X_train, train_labels)


In [41]:
y_predict = rfcl.predict(X_test)
print(rfcl.score(X_test , test_labels))
print(metrics.confusion_matrix(test_labels, y_predict))

0.74
[[191  23]
 [ 55  31]]
